#include <stdio.h>
#include <string.h>
#include <stdlib.h>


#include "dap_debugger_types.h"
#include "dap_debugger_commands.h"


// Define the command table
const DebuggerCommand commands[] = {
    {
        .name = "help",
        .alias = "h",
        .alias2 = "?",
        .syntax = "help [command]",
        .description = "Show help information for commands",
        .request_format = NULL,
        .response_format = NULL,
        .events = NULL,
        .has_options = true,
        .option_types = "command",
        .option_descriptions = "Command to show help for",
        .examples = "help|Show all commands|help break|Show help for break command",
        .category = CATEGORY_OTHER,
        .implemented = true,
        .handler = handle_help_command
    },
    {
        .name = "exit",
        .alias = "quit",
        .alias2 = "q",
        .syntax = "exit",
        .description = "Exit the debugger",
        .request_format = NULL,
        .response_format = NULL,
        .events = NULL,
        .has_options = false,
        .option_types = NULL,
        .option_descriptions = NULL,
        .examples = "exit|Exit the debugger",
        .category = CATEGORY_OTHER,
        .implemented = true,
        .handler = handle_quit_command
    },
    {
        .name = "continue",
        .alias = "cont",
        .alias2 = "c",
        .syntax = "continue [thread_id]",
        .description = "Continue execution",
        .request_format = "{\"threadId\": number, \"singleThread\": boolean}",
        .response_format = "{\"allThreadsContinued\": boolean}",
        .events = "continued",
        .has_options = true,
        .option_types = "thread_id",
        .option_descriptions = "Optional thread ID to continue",
        .examples = "continue|Continue all threads|continue 1|Continue thread 1",
        .category = CATEGORY_EXECUTION_CONTROL,
        .implemented = true,
        .handler = handle_continue_command
    },
    {
        .name = "next",
        .alias = "over",
        .alias2 = "n",
        .syntax = "next [thread_id]",
        .description = "Step over next line",
        .request_format = "{\"threadId\": number, \"singleThread\": boolean}",
        .response_format = "{\"allThreadsContinued\": boolean}",
        .events = "continued",
        .has_options = true,
        .option_types = "thread_id",
        .option_descriptions = "Optional thread ID to step",
        .examples = "next|Step over in current thread|next 1|Step over in thread 1",
        .category = CATEGORY_EXECUTION_CONTROL,
        .implemented = true,
        .handler = handle_next_command
    },
    {
        .name = "stepIn",
        .alias = "step",
        .alias2 = "s",
        .syntax = "stepIn [thread_id]",
        .description = "Step into function call",
        .request_format = "{\"threadId\": number, \"singleThread\": boolean}",
        .response_format = "{\"allThreadsContinued\": boolean}",
        .events = "continued",
        .has_options = true,
        .option_types = "thread_id",
        .option_descriptions = "Optional thread ID to step",
        .examples = "step|Step into in current thread|step 1|Step into in thread 1",
        .category = CATEGORY_EXECUTION_CONTROL,
        .implemented = true,
        .handler = handle_step_command
    },
    {
        .name = "stepOut",
        .alias = "step-out",
        .alias2 = "o",
        .syntax = "stepOut [thread_id]",
        .description = "Step out of current function",
        .request_format = "{\"threadId\": number, \"singleThread\": boolean}",
        .response_format = "{\"allThreadsContinued\": boolean}",
        .events = "continued",
        .has_options = true,
        .option_types = "thread_id",
        .option_descriptions = "Optional thread ID to step",
        .examples = "step-out|Step out in current thread|step-out 1|Step out in thread 1",
        .category = CATEGORY_EXECUTION_CONTROL,
        .implemented = true,
        .handler = handle_step_out_command
    },
    {
        .name = "setBreakpoints",
        .alias = "break",
        .alias2 = "b",
        .syntax = "setBreakpoints <line> [file]",
        .description = "Set a breakpoint",
        .request_format = "{\"source\": {\"path\": string}, \"breakpoints\": [{\"line\": number}]}",
        .response_format = "{\"breakpoints\": [{\"verified\": boolean, \"line\": number}]}",
        .events = "breakpoint",
        .has_options = true,
        .option_types = "line|file",
        .option_descriptions = "Line number|Optional file path",
        .examples = "break 42|Set breakpoint at line 42 in current file|break 42 main.c|Set breakpoint at line 42 in main.c",
        .category = CATEGORY_BREAKPOINTS,
        .implemented = true,
        .handler = handle_break_command
    },
    {
        .name = "setExceptionBreakpoints",
        .alias = "exception",
        .alias2 = "ex",
        .syntax = "setExceptionBreakpoints [filters]",
        .description = "Set exception breakpoints",
        .request_format = "{\"filters\": [string], \"filterOptions\": [{\"filterId\": string, \"condition\": string}]}",
        .response_format = "{\"breakpoints\": [{\"verified\": boolean, \"id\": number, \"message\": string}]}",
        .events = "stopped (reason: exception)",
        .has_options = true,
        .option_types = "all|uncaught|custom",
        .option_descriptions = "Break on all exceptions|Break on uncaught exceptions|Custom exception filter names",
        .examples = "exception|Set default exception breakpoint (uncaught)|exception all|Break on all exceptions|exception all,uncaught|Break on all and uncaught exceptions",
        .category = CATEGORY_BREAKPOINTS,
        .implemented = true,
        .handler = handle_exception_command
    },
    {
        .name = "source",
        .alias = "list",
        .alias2 = "l",
        .syntax = "source [file]",
        .description = "Get source code content",
        .request_format = "{\"source\": {\"path\": string}}",
        .response_format = "{\"content\": string}",
        .events = NULL,
        .has_options = true,
        .option_types = "file",
        .option_descriptions = "Optional file path to get source",
        .examples = "source|Get current file|source file.c|Get source for file.c",
        .category = CATEGORY_SOURCE,
        .implemented = true,
        .handler = handle_source_command
    },
    {
        .name = "stackTrace",
        .alias = "backtrace",
        .alias2 = "bt",
        .syntax = "stackTrace [thread_id]",
        .description = "Show stack trace",
        .request_format = "{\"threadId\": number}",
        .response_format = "{\"stackFrames\": [{\"id\": number, \"name\": string, \"line\": number, \"column\": number}]}",
        .events = NULL,
        .has_options = true,
        .option_types = "thread_id",
        .option_descriptions = "Optional thread ID",
        .examples = "stackTrace|Show stack trace for current thread|stackTrace 1|Show stack trace for thread 1",
        .category = CATEGORY_STACK_AND_VARIABLES,
        .implemented = true,
        .handler = handle_stackTrace_command
    },
    {
        .name = "variables",
        .alias = "vars",
        .alias2 = "v",
        .syntax = "variables [reference [depth]]",
        .description = "Show variables with hierarchical display and type information",
        .request_format = "{\"variablesReference\": number}",
        .response_format = "{\"variables\": [{\"name\": string, \"value\": string, \"type\": string, \"variablesReference\": number}]}",
        .events = NULL,
        .has_options = true,
        .option_types = "reference|depth",
        .option_descriptions = "Optional variables reference|Optional maximum recursion depth (default: 1)",
        .examples = "variables|Show all variables in all scopes|variables 1001|Show variables for reference 1001|variables 1001 2|Show variables for reference 1001 with maximum depth of 2",
        .category = CATEGORY_STACK_AND_VARIABLES,
        .implemented = true,
        .handler = handle_variables_command
    },
    {
        .name = "threads",
        .alias = "t",
        .syntax = "threads",
        .description = "List threads",
        .request_format = "{}",
        .response_format = "{\"threads\": [{\"id\": number, \"name\": string}]}",
        .events = NULL,
        .has_options = false,
        .option_types = NULL,
        .option_descriptions = NULL,
        .examples = "threads|List all threads",
        .category = CATEGORY_THREADS,
        .implemented = true,
        .handler = handle_threads_command
    },
    {
        .name = "scopes",
        .alias = "s",
        .syntax = "scopes [frame_id]",
        .description = "Show scopes for frame",
        .request_format = "{\"frameId\": number}",
        .response_format = "{\"scopes\": [{\"name\": string, \"variablesReference\": number}]}",
        .events = NULL,
        .has_options = true,
        .option_types = "frame_id",
        .option_descriptions = "Optional frame ID",
        .examples = "scopes|Show scopes for current frame|scopes 1|Show scopes for frame 1",
        .category = CATEGORY_STACK_AND_VARIABLES,
        .implemented = true,
        .handler = handle_scopes_command
    },
    {
        .name = "debugmode",
        .alias = "dm",
        .syntax = "debugmode [on|off]",
        .description = "Toggle debug mode",
        .request_format = NULL,
        .response_format = NULL,
        .events = NULL,
        .has_options = true,
        .option_types = "on|off",
        .option_descriptions = "Enable or disable debug mode",
        .examples = "debugmode|Toggle debug mode|debugmode on|Enable debug mode|debugmode off|Disable debug mode",
        .category = CATEGORY_OTHER,
        .implemented = true,
        .handler = handle_debugmode_command
    },
    {
        .name = "disassemble",
        .alias = "da",
        .syntax = "disassemble <memory_reference> [-o offset] [-i instruction_offset] [-c count] [-s]",
        .description = "Disassemble code at memory location",
        .request_format = "{\"memoryReference\": string, \"offset\": number, \"instructionOffset\": number, \"instructionCount\": number, \"resolveSymbols\": boolean}",
        .response_format = "{\"instructions\": [{\"address\": string, \"instruction\": string, \"symbol\": string}]}",
        .events = NULL,
        .has_options = true,
        .option_types = "memory_reference|offset|instruction_offset|count|resolve_symbols",
        .option_descriptions = "Memory reference and optional parameters",
        .examples = "disassemble 0x1000|Disassemble at address 0x1000|disassemble main -c 10|Disassemble 10 instructions at main|disassemble 0x1000 -s|Disassemble with symbol resolution",
        .category = CATEGORY_DISASSEMBLY,
        .implemented = true,
        .handler = handle_disassemble_command
    },
    {
        .name = "pause",
        .alias = "pause",
        .alias2 = "p",
        .syntax = "pause [thread_id]",
        .description = "Pause execution",
        .request_format = "{\"threadId\": number}",
        .response_format = "{}",
        .events = "stopped (reason: pause)",
        .has_options = true,
        .option_types = "thread_id",
        .option_descriptions = "Optional thread ID to pause",
        .examples = "pause|Pause all threads|pause 1|Pause thread 1",
        .category = CATEGORY_EXECUTION_CONTROL,
        .implemented = true,
        .handler = handle_pause_command
    },
    {
        .name = "evaluate",
        .alias = "eval",
        .alias2 = "e",
        .syntax = "evaluate <expression> [frame_id] [context]",
        .description = "Evaluate expression",
        .request_format = "{\"expression\": string, \"frameId\": number, \"context\": string}",
        .response_format = "{\"result\": string, \"type\": string, \"variablesReference\": number}",
        .events = NULL,
        .has_options = true,
        .option_types = "expression|frame_id|context",
        .option_descriptions = "Expression to evaluate|Optional frame ID|Optional context (watch, repl, hover)",
        .examples = "evaluate x|Evaluate variable x|evaluate x+1 0|Evaluate x+1 in frame 0|evaluate myVar 0 watch|Evaluate myVar in watch context",
        .category = CATEGORY_STACK_AND_VARIABLES,
        .implemented = true,
        .handler = handle_evaluate_command
    },
    {
        .name = "launch",
        .alias = "run",
        .alias2 = "r",
        .syntax = "launch [program_file]",
        .description = "Launch debug session",
        .request_format = "{\"program\": string, \"stopOnEntry\": boolean}",
        .response_format = "{}",
        .events = "initialized, stopped",
        .has_options = true,
        .option_types = "program_file",
        .option_descriptions = "Optional program file to launch",
        .examples = "launch|Launch current program|launch hello.out|Launch specific program",
        .category = CATEGORY_EXECUTION_CONTROL,
        .implemented = true,
        .handler = handle_launch_command
    },
    {
        .name = "readMemory",
        .alias = "memory",
        .alias2 = "x",
        .syntax = "readMemory <memory_reference> [count] [offset]",
        .description = "Read and dump memory at specified address",
        .request_format = "{\"memoryReference\": string, \"count\": number, \"offset\": number}",
        .response_format = "{\"address\": string, \"data\": string, \"unreadableBytes\": number}",
        .events = NULL,
        .has_options = true,
        .option_types = "memory_reference|count|offset",
        .option_descriptions = "Memory address and optional byte count and offset",
        .examples = "readMemory 0x1000|Read 16 bytes at 0x1000|readMemory 0x1000 64|Read 64 bytes|readMemory main 32 8|Read 32 bytes at main+8",
        .category = CATEGORY_DISASSEMBLY,
        .implemented = true,
        .handler = handle_read_memory_command
    },
    {
        .name = "capabilities",
        .alias = "srv",
        .alias2 = "server",
        .syntax = "capabilities",
        .description = "Show server capabilities and supported features",
        .request_format = "{}",
        .response_format = "{\"capabilities\": object}",
        .events = NULL,
        .has_options = false,
        .option_types = NULL,
        .option_descriptions = NULL,
        .examples = "capabilities|Show server capabilities|srv|Show server info",
        .category = CATEGORY_OTHER,
        .implemented = true,
        .handler = handle_capabilities_command
    },
    { NULL } // Terminator
}; 
